sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-test -f Dockerfile.dev .

script:
  - docker run docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react-aws
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-618316596689"
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"